// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1:string):Promise<string>;

export function GetConfig():Promise<Record<string, any>>;

export function GetMemories(arg1:number):Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function ToggleCapture(arg1:boolean):Promise<boolean>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;
